Rails.application.config.assets.version = "1.0"

# Add additional assets to the asset load path.
Rails.application.config.assets.paths << Rails.root.join("app/assets/builds")

# Make the importmap JavaScript (app/javascript/application.js and the
# Stimulus controllers) available to Sprockets so importmap pins resolve.
Rails.application.config.assets.paths << Rails.root.join("app/javascript")

# Explicitly declare the Tailwind-built stylesheet as precompiled so
# `stylesheet_link_tag "tailwind"` resolves it (it is generated by the
# tailwindcss:build task into app/assets/builds/tailwind.css).
Rails.application.config.assets.precompile += %w[tailwind.css]
